### ISSUE TITLE
Change name to wd74b

### ISSUE THREAD

**Issue by OdnetninI** [iimarckus/pokered#59]
I was searching and wd74b at wram is the flag that controls if the players has the pokedex.

wd74b could be: W_ISPOKEDEXOWNED or something similar

**Comment by dannye** [comment]
While it is true that it would be better to have a more descriptive name than wd74b, only bit 5 of that byte determines if the player has the Pokedex. This address is more generally a game progress flag, meaning each bit is a flag for a different game event.

In order to clean this up, I am considering changing wram.asm to something like:
```
wFlags_d74b:: ds 1
[...]
POKEDEX_OWNED EQU 5
```
This way, code can check if the player has the Pokedex by using:
```
ld a, [wFlags_d74b]
bit POKEDEX_OWNED, a
```

**Comment by yenatch** [comment]
this flag is enumerated along with a host of others. here is one way it could be implemented

constants/event_flags.asm
```asm
check_flag: macro
ld a, [wEventFlags + \1 / 8]
bit \1 % 8, a
endm

__enum__ = 0
enum flag_1
enum flag_2
enum flag_3
...
enum pokedex_owned
...
NUM_EVENT_FLAGS equ __enum__
```

wram.asm
```asm
wEventFlags:
    flag_array NUM_EVENT_FLAGS
```

wherever
```asm
check_flag pokedex_owned
```

**Comment by dannye** [comment]
Handled by https://github.com/iimarckus/pokered/pull/107
